name: ci

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - README.md

permissions:
    packages: write

jobs:
    docker:
        strategy:
            matrix:
                rust_version: ['stable', '1.82', '1.81', '1.80', '1.79']
                include:
                - rust_version: 'stable'
                  docker_tag: 'latest'
            max-parallel: 1

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  build-args: |
                    RUST_VERSION=${{matrix.rust_version}}
                  file: ./Dockerfile
                  push: ${{github.ref == 'refs/heads/main'}}
                  tags: ghcr.io/arma-place/windows-msvc-rs:${{matrix.docker_tag || matrix.rust_version}}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
